name: FBFunc CI

on:
  push:
    paths:
      - 'functions/**'
      - '.github/workflows/nodejs_fb_ci.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm install, build, and test the functions
      working-directory: ./functions
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Where we are
      run: |
        echo $PWD
        ls -lasi
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master 
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: brettski-firebase
      
