name: FBFunc CI

on:
  push:
    - 'fbfunc/**'
    - '.github/workflows/nodejs_fb_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm install, build, and test
      working-directory: ./fbfunc
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
