name: Node CI

on:
  push:
    paths: 
      - 'nodesvr/**'
      - '.github/workflows/nodejs_ci.yml'

jobs:
  build-deploy:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        #node-version: ${{ matrix.node-version }}
        node-version: 10.x
    - name: npm install, build, and test
      working-directory: ./nodesvr
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
    
#    steps:
#    - name: Check out code
#      uses: actions/checkout@1
    - name: GCP Authentication
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_CLOUD_AUTH }}
        
    - name: List Functions
      uses: actions/gcloud/cli@master
      env:
        CLOUDSDK_CORE_PROJECT: brettski-learning-gcp
      with:
        args: functions list
                  
    - name: Deploy Function getUSome
      uses: actions/gcloud/cli@master
      env:
        CLOUDSDK_CORE_PROJECT: brettski-learning-gcp
      with:
        args: functions deploy getUSome --runtime nodejs10 --trigger-http --source $PWD/nodesvr
